### ISSUE TITLE
search.php causes 403 Forbidden error

### ISSUE THREAD

**Issue by PirateBay007** [piratebayproxy/UnblockedPiratebayClean#14]
I've been running this script for a while without issues. However I now get a "403 forbidden error" on the search.php page. Think it may have something to do with my Apache settings (think it updated from 2.2 to 2.4 automatically)

I'm running Centos 6 32bit, with CWP 6 running Apache 2.4.23.

When I delete the following line 
"curl_setopt($ch, CURLOPT_URL, $url);"
from the functions.php file the 403 errors goes and I just get a white screen so I'm guessing its a problem with the new Apache version not liking this line in the script? 

anyone got any ideas on how to solve this?

**Comment by piratebayproxy** [comment]
If you have shell access to the server, try accessing tpb using the curl command, e.g. 'curl -v https://thepiratebay.org/search/linux/0/99/0' and see what you get.  If you get a 403, that means your ip may have been blocked by tpb.  There were some ddos attacks on tpb a few weeks ago which led to many ip addresses getting blocked by tpb.  Otherwise, try the alternative php script and see if that works.
