### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by mArzyu** [piratebayproxy/UnblockedPiratebayClean#16]
Hello, I'm using this script on a shared host but no matter what, after some time the site gets the message

403 Forbidden
nginx/1.13.8

I see some other sites using same script and don't have same problem.

Some help would be appreciated.

Thanks

**Comment by piratebayproxy** [comment]
This is likely caused by your server IP getting banned by TPB. I haven't found a pattern as to why they will ban certain IP addresses. It could be that they don't want new proxy sites or perhaps some proxy sites are being used to spam tpb. Torrent sites might mistake proxy traffic as a DMCA bot or DDOS attack as well.
The only workaround I can think of is to move to another host or get another IP address somehow.

**Comment by mArzyu** [comment]
can you recommend me a good offshore vps host?

**Comment by piratebayproxy** [comment]
You can check out offshorededi, hostkey, and bahnhof. Otherwise do a google search for something like offshore vps.
